// Code generated by protoc-gen-go. DO NOT EDIT.
// source: go-microservice-examples/api/hotel/proto/hotel.proto

package hotel

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import proto1 "go-microservice-examples/srv/profile/proto"
import proto2 "go-microservice-examples/srv/rate/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	InDate               string   `protobuf:"bytes,1,opt,name=inDate,proto3" json:"inDate,omitempty"`
	OutDate              string   `protobuf:"bytes,2,opt,name=outDate,proto3" json:"outDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_hotel_127ac82b98249a04, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetInDate() string {
	if m != nil {
		return m.InDate
	}
	return ""
}

func (m *Request) GetOutDate() string {
	if m != nil {
		return m.OutDate
	}
	return ""
}

type Response struct {
	Hotels               []*proto1.Hotel    `protobuf:"bytes,1,rep,name=hotels,proto3" json:"hotels,omitempty"`
	RatePlans            []*proto2.RatePlan `protobuf:"bytes,2,rep,name=ratePlans,proto3" json:"ratePlans,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_hotel_127ac82b98249a04, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetHotels() []*proto1.Hotel {
	if m != nil {
		return m.Hotels
	}
	return nil
}

func (m *Response) GetRatePlans() []*proto2.RatePlan {
	if m != nil {
		return m.RatePlans
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "hotel.Request")
	proto.RegisterType((*Response)(nil), "hotel.Response")
}

func init() {
	proto.RegisterFile("go-microservice-examples/api/hotel/proto/hotel.proto", fileDescriptor_hotel_127ac82b98249a04)
}

var fileDescriptor_hotel_127ac82b98249a04 = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0xdd, 0xca, 0x6e, 0xed, 0x08, 0x15, 0x72, 0x90, 0x65, 0x4f, 0x65, 0x0f, 0x52, 0xc4,
	0xee, 0xc2, 0xd6, 0x83, 0xe0, 0xd5, 0x83, 0x47, 0xc9, 0x2f, 0x30, 0x96, 0x51, 0x03, 0xe9, 0x26,
	0x66, 0xd2, 0xe2, 0xcf, 0x97, 0x4c, 0xb2, 0x7a, 0xb2, 0xb7, 0xf7, 0xe6, 0xcd, 0x97, 0xbc, 0x04,
	0xee, 0x3f, 0xec, 0x66, 0xaf, 0x77, 0xde, 0x12, 0xfa, 0xa3, 0xde, 0xe1, 0x06, 0xbf, 0xd5, 0xde,
	0x19, 0xa4, 0x5e, 0x39, 0xdd, 0x7f, 0xda, 0x80, 0xa6, 0x77, 0xde, 0x06, 0x9b, 0x74, 0xc7, 0x5a,
	0x94, 0x6c, 0x9a, 0x87, 0x7f, 0x61, 0xf2, 0xc7, 0x88, 0xbd, 0x6b, 0x83, 0x19, 0xcf, 0x2e, 0x1d,
	0xd0, 0x0c, 0x27, 0x49, 0xaf, 0xc2, 0x84, 0x45, 0x99, 0x98, 0xf6, 0x11, 0xe6, 0x12, 0xbf, 0x0e,
	0x48, 0x41, 0x5c, 0x43, 0xa5, 0xc7, 0x27, 0x15, 0xb0, 0x2e, 0x56, 0xc5, 0x7a, 0x21, 0xb3, 0x13,
	0x35, 0xcc, 0xed, 0x21, 0x70, 0x30, 0xe3, 0x60, 0xb2, 0xed, 0x2b, 0x5c, 0x48, 0x24, 0x67, 0x47,
	0x42, 0x71, 0x03, 0x15, 0xf7, 0xa7, 0xba, 0x58, 0x9d, 0xaf, 0x2f, 0x87, 0x65, 0x37, 0x95, 0x7b,
	0x8e, 0x63, 0x99, 0x53, 0x71, 0x07, 0x8b, 0x78, 0xfd, 0x8b, 0x51, 0x23, 0xd5, 0xb3, 0xbc, 0xca,
	0x85, 0x64, 0x1e, 0xcb, 0xbf, 0x85, 0x61, 0x0b, 0x25, 0xe3, 0xe2, 0x16, 0xca, 0x98, 0x93, 0x58,
	0x76, 0xe9, 0xcf, 0x72, 0xeb, 0xe6, 0xea, 0xd7, 0xa7, 0x22, 0xed, 0xd9, 0x5b, 0xc5, 0x4f, 0xdb,
	0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x62, 0x65, 0x9e, 0x96, 0x87, 0x01, 0x00, 0x00,
}
